# Generated by Django 3.1.4 on 2021-01-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210108_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='prince',
            field=models.IntegerField(default=0),
        ),
    ]
