# Generated by Django 3.1.4 on 2021-01-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_prince'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='prince',
            new_name='price',
        ),
    ]
