# Generated by Django 3.1.4 on 2021-01-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210109_1728'),
        ('carts', '0011_auto_20210109_2256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
