# Generated by Django 3.1.3 on 2020-12-31 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Product id'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Price Level'),
        ),
    ]
