# Generated by Django 3.1.4 on 2021-01-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210109_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product id'),
        ),
    ]
