# Generated by Django 3.1.4 on 2021-01-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210109_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
