# Generated by Django 3.1.4 on 2021-01-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Product id'),
        ),
    ]
