# Generated by Django 3.1.4 on 2021-01-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210112_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, default=0, max_length=300),
        ),
    ]
