# Generated by Django 3.1.4 on 2021-01-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210112_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_size',
            field=models.CharField(blank=True, default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
